package zeklandia.desktop.reddit.client;

import com.omrlnr.jreddit.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Zeklandia
 */

public class ClientMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public ClientMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redditScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        redditScrollPane.setBackground(null);
        redditScrollPane.setBorder(null);
        redditScrollPane.setForeground(new java.awt.Color(50, 50, 50));
        redditScrollPane.setFont(null);
        redditScrollPane.setName("redditScrollPane"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redditScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redditScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main() {

        try {
            // Set System L&F
        UIManager.setLookAndFeel(
        UIManager.getSystemLookAndFeelClassName());
        } 
        catch (UnsupportedLookAndFeelException e) {
       // handle exception
        }
        catch (ClassNotFoundException e) {
       // handle exception
        }
        catch (InstantiationException e) {
       // handle exception
        }
        catch (IllegalAccessException e) {
       // handle exception
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientMain client = new ClientMain();
                client.setLocationRelativeTo(null);
                client.setVisible(true);
                client.setTitle("Java-Reddit");
                
            }
        });
        
        ClientLogin.main();
        
    }
    
    public static void userLogin(String username, String password) {
        
        
        User user = new User(username, password);
        try {
            user.connect();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(ClientLogin.buttonLogin, "Login failed");
            ClientLogin.main();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane redditScrollPane;
    // End of variables declaration//GEN-END:variables

}